<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Fixture.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Fixture.Lib\Fixture.Lib.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" Version="4.0.1" />
        <Using Include="Xunit" />
    </ItemGroup>
</Project>
