<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Lunate.Extensibility.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Lunate.Extensibility.Abstractions/Lunate.Extensibility.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" Version="4.0.1" />
        <Using Include="Xunit" />
    </ItemGroup>
</Project>
