<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>CalculatorLib.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\CalculatorLib\CalculatorLib.csproj" />
    </ItemGroup>
</Project>
