<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Lunate.Protocols.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Lunate.Protocols/Lunate.Protocols.csproj" />
        <ProjectReference
            Include="../tools/TestMcpServer/TestMcpServer.csproj"
            ReferenceOutputAssembly="false"
        />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" Version="4.0.1" />
        <Using Include="Xunit" />
    </ItemGroup>
</Project>
