<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>MemoryProviderExtension</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../../src/Lunate.Extensibility.Abstractions/Lunate.Extensibility.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="extension.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
