<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>TemplateExtension.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../src/Lunate.Ai/Lunate.Ai.csproj" />
        <ProjectReference Include="../../../src/Lunate.Extensibility.Abstractions/Lunate.Extensibility.Abstractions.csproj" />
        <ProjectReference Include="../../../src/Lunate.Extensibility.Testing/Lunate.Extensibility.Testing.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" Version="4.0.1" />
        <Using Include="Xunit" />
    </ItemGroup>

    <Target Name="CopyTemplateExtension" AfterTargets="Build">
        <MSBuild
            Projects="$(MSBuildThisFileDirectory)../TemplateExtension/TemplateExtension.csproj"
            Targets="Build"
            Properties="Configuration=$(Configuration)"
        />
        <ItemGroup>
            <TemplateExtensionFiles Include="$(MSBuildThisFileDirectory)../TemplateExtension/bin/$(Configuration)/$(TargetFramework)/**/*" />
        </ItemGroup>
        <Copy
            SourceFiles="@(TemplateExtensionFiles)"
            DestinationFolder="$(OutDir)TemplateExtension/%(RecursiveDir)"
            SkipUnchangedFiles="true"
        />
    </Target>
</Project>
