<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>S6.Harness</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="XenoAtom.Terminal.UI" Version="3.10.0" />
        <PackageReference Include="XenoAtom.Terminal.UI.Extensions.Markdown" Version="3.10.0" />
    </ItemGroup>
</Project>
